### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by Sim4n6** [jcsalterego/historian#13]
hi @jcsalterego nice script you have here, I would like to suggest this : 
 
- [ ] Shell check the script
- [ ] Colorizing echo
- [ ] Getting rid of checking the existence of $HOME 
- [ ] Add description for script at the beginning
- [ ] apply [best practices](http://fahdshariff.blogspot.com/2013/10/shell-scripting-best-practices.html)

please assign this issue to me, I will PR later

**Comment by jcsalterego** [comment]
> Shell check the script

What do you mean here?

> Colorizing echo

I think I will skip that for now since I don't want to add complexity to the script.

> Getting rid of checking the existence of $HOME

The existence check is such that if somehow this script runs outside the context of a login shell, it won't do weird things.

> Add description for script at the beginning

That's a good idea, though I suppose I bias towards a smaller script. It's already getting pretty large...

> apply best practices

One day!

**Comment by Sim4n6** [comment]
Shellcheck is shell checker solution
